name       : template-glib
version    : 3.34.0
release    : 5
source     :
    - https://download.gnome.org/sources/template-glib/3.34/template-glib-3.34.0.tar.xz : 216bef6ac3607666b8ca72b936467f7020ce6421c02755c301d079576c9c3dfd
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Template-GLib is a library to help you generate text based on a template and user defined state.
description: |
    Template-GLib is a library to help you generate text based on a template and user defined state. Template-GLib does not use a language runtime, so it is safe to use from any GObject-Introspectable language.
builddeps  :
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
