name       : template-glib
version    : 3.36.1
release    : 10
source     :
    - https://download.gnome.org/sources/template-glib/3.36/template-glib-3.36.1.tar.xz : 3b167a17385ad745afbe20fadf8106c66d30c5bd746d5aa1d9bdb7e803f6a503
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Template-GLib is a library to help you generate text based on a template and user defined state.
description: |
    Template-GLib is a library to help you generate text based on a template and user defined state. Template-GLib does not use a language runtime, so it is safe to use from any GObject-Introspectable language.
builddeps  :
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
