name       : template-glib
version    : 3.32.0
release    : 3
source     :
    - https://download.gnome.org/sources/template-glib/3.32/template-glib-3.32.0.tar.xz : 39a334f5db404fa8b225224766684f2f63f5ec4cf4e971cfc513f1db35e81fbc
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Template-GLib is a library to help you generate text based on a template and user defined state.
description: |
    Template-GLib is a library to help you generate text based on a template and user defined state. Template-GLib does not use a language runtime, so it is safe to use from any GObject-Introspectable language.
builddeps  :
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
